In [2]:
from bosonicplus.newpackage.base import State
import numpy as np
from thewalrus.symplectic import squeezing, beam_splitter, expand, xxpp_to_xpxp, expand_vector

S1 = xxpp_to_xpxp(expand(squeezing(1,np.pi), [0], 2))
B = xxpp_to_xpxp(beam_splitter(np.pi/4, 0))
S2 = xxpp_to_xpxp(expand(squeezing(1,0), [1], 2))


s1 = State(2)
print(s1.ordering)
s1.apply_symplectic(B@S1@S2)
s1.apply_loss(np.array([0.5,1.0]),np.array([0,0]))
print(s1.covs)

s1.to_xpxp()
print(s1.ordering)
print(s1.covs)

xxpp
[[[ 2.38109785e+00 -1.11040575e-16  2.56457759e+00 -1.57035087e-16]
  [-1.11040575e-16  2.38109785e+00 -1.57035087e-16 -2.56457759e+00]
  [ 2.56457759e+00 -1.57035087e-16  3.76219569e+00 -2.22081149e-16]
  [-1.57035087e-16 -2.56457759e+00 -2.22081149e-16  3.76219569e+00]]]
xpxp
[array([[ 2.38109785e+00,  2.56457759e+00, -1.11040575e-16,
        -1.57035087e-16],
       [ 2.56457759e+00,  3.76219569e+00, -1.57035087e-16,
        -2.22081149e-16],
       [-1.11040575e-16, -1.57035087e-16,  2.38109785e+00,
        -2.56457759e+00],
       [-1.57035087e-16, -2.22081149e-16, -2.56457759e+00,
         3.76219569e+00]])]


In [10]:
from bosonicplus.newpackage.gbs import build_interferometer
from bosonicplus.interferometers.construct import build_interferometer as old
from bosonicplus.interferometers.parameters import gen_interferometer_params
from time import time

In [14]:
nmodes = 10
params = gen_interferometer_params(nmodes, -13)
t0 = time()
state = build_interferometer(params, nmodes)
print(state.ordering)
t1 = time()

ti = time()
circuit = old(params, nmodes)
tf = time()
state.to_xpxp()
print(state.ordering)
print(np.allclose(circuit.covs, state.covs))

print('sf', tf-ti)
print('bosonicplus', t1-t0)

print((t1-t0)/(tf-ti))

xxpp
xpxp
True
sf 0.008471012115478516
bosonicplus 0.010821104049682617
1.2774275260343373
