In [1]:
from bosonicplus.base import State
from thewalrus.symplectic import squeezing, xxpp_to_xpxp, xpxp_to_xxpp
from thewalrus.decompositions import williamson
import numpy as np

In [2]:
state = State(2)
state.apply_symplectic_fast(xxpp_to_xpxp(squeezing(1,0)),[0])
state.apply_symplectic_fast(xxpp_to_xpxp(squeezing(0.5,0)),[1])
sigma = state.covs
print(sigma)
state.apply_loss(np.array([0.5,1]),np.zeros(2))

print(state.covs)


[[[0.13533528 0.         0.         0.        ]
  [0.         7.3890561  0.         0.        ]
  [0.         0.         0.36787944 0.        ]
  [0.         0.         0.         2.71828183]]]
[[[0.56766764 0.         0.         0.        ]
  [0.         4.19452805 0.         0.        ]
  [0.         0.         0.36787944 0.        ]
  [0.         0.         0.         2.71828183]]]


In [3]:
etas = np.array([0.5,1])
nbars = np.zeros(2)
hbar = 2

X1 = np.diag(np.repeat(np.sqrt(etas),2))
Y1 = np.diag(np.repeat( (1-etas) * hbar / 2 * (2*nbars + 1) ,2 ))
print(X1, Y1) #in xpxp

X2 = xxpp_to_xpxp(np.diag(np.repeat(np.sqrt(etas),2)))
Y2 = xxpp_to_xpxp(np.diag(np.repeat( (1-etas) * hbar / 2 * (2*nbars + 1) ,2 )))

print(X2,Y2) #Should be wrong ordering

print(X1@sigma@X1.T + Y1) #Gives same result as bosonicplus
print(np.allclose(state.covs, X1@sigma@X1.T + Y1))
print(X2@sigma@X2.T + Y2) #Gives weird result
print(np.allclose(state.covs, X2@sigma@X2.T + Y2))

[[0.70710678 0.         0.         0.        ]
 [0.         0.70710678 0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         0.         1.        ]] [[0.5 0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]
[[0.70710678 0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         0.70710678 0.        ]
 [0.         0.         0.         1.        ]] [[0.5 0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  0. ]]
[[[0.56766764 0.         0.         0.        ]
  [0.         4.19452805 0.         0.        ]
  [0.         0.         0.36787944 0.        ]
  [0.         0.         0.         2.71828183]]]
True
[[[0.56766764 0.         0.         0.        ]
  [0.         7.3890561  0.         0.        ]
  [0.         0.         0.68393972 0.        ]
  [0.         0.         0.         2.71828183]]]
False
